apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: v04qw4gas-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v04qw4gas-python 
  name: v04qw4gas-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: v04qw4gas-python
    weight: 100 
