apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: v04qw4gas-python-gitops
  description: This is GitOps manifest for v04qw4gas-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: v04qw4gas-python
    backstage.io/kubernetes-id: v04qw4gas-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: v04qw4gas-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:v04qw4gas-python
